### PR TITLE
Add new CLI target, add old GUI target to new build, and LICENSE

### PR DESCRIPTION
**Pull request by jbakosi**
Add GUI target to new build

Also:
* Includes the CLI (as far as I got with it: basic commands work, can connect/disconnect/reconnect to daemon).
* Added a LICENSE, BSD-3. (That's ~MIT + the 3rd BSD clause.) Any issues?
* Cleaned up (socket) `Client` + fixed a bug with it.

### CODE REVIEW

**Comment by jbakosi** [comment]
The automated builds fail because I still need to update the docker image with some new libs, like daniele77/cli and dokun-ui. Will do that soon.

**Comment by layters** [comment]
> Add GUI target to new build
> 
> Also:
> 
>     * Includes the CLI (as far as I got with it: basic commands work, can connect/disconnect/reconnect to daemon).
> 
>     * Added a LICENSE, BSD-3. (That's ~MIT + the 3rd BSD clause.) Any issues?
> 
>     * Cleaned up (socket) `Client` + fixed a bug with it.

Good job on the CLI and the client code fix.

I have no problem with BSD but what was the point of changing it from MIT lol (I know they are basically almost the same).

**Comment by jbakosi** [comment]
The difference between MIT and 3-clause BSD is that the following is only in BSD-3:
> 3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission

I tend to prefer that.

**Comment by layters** [comment]
> The difference between MIT and 3-clause BSD is that the following is only in BSD-3:
> 
> > 3. Neither the name of the copyright holder nor the names of its contributors
> >    may be used to endorse or promote products derived from this software without
> >    specific prior written permission
> 
> I tend to prefer that.

That was the only difference I could find which gives it an advantage over MIT.
We'll go with BSD-3 then.

**Comment by layters** [comment]
A few spelling errors here and there, but that can be easily fixed so it's not really that important at all.
BTW, wouldn't the <> header guards be more appropriate for external libraries and the " " header guards be better for the core internal source files?
Also, how come you removed the `neroshop::Client::function_name() {}` and added `using namespace neroshop;` in `client.cpp`? Just to be safe (from naming conflicts with other libs using the word Client), I only used it in `main.cpp`

**Comment by jbakosi** [comment]
> A few spelling errors here and there, but that can be easily fixed so it's not really that important at all. BTW, wouldn't the <> header guards be more appropriate for external libraries and the " " header guards be better for the core internal source files?

I thought `<>` for system libs and `""` for non-system libs. There is differences in how the standard wants it I think. But I think the builds picks up the correct ones now. I had to struggle with that a bit since monero has a `string.h`, which is also a system lib, so when it picked up the wrong one it is bad. But now it's fine.

> Also, how come you removed the `neroshop::Client::function_name() {}` and added `using namespace neroshop;` in `client.cpp`? Just to be safe (from naming conflicts with other libs using the word Client), I only used it in `main.cpp`.

I don't remember the exact instance. But I think it was when there is no body of the function then why bother put it in the `.cpp` file, it just leads to more code. If I remember correctly...

In a `.cpp` it is safer to use `using namespace neroshop;` because it leads to less verbose code. This would lead to more dangerous code in a header because it can have unintended consequences when the header is included in various other headers and `.cpp` files which then it can change the meaning of downstream definitions and can also lead to collisions.

**Comment by layters** [comment]
Right. Thanks for the explanations.

**Review by layters — APPROVED** [review]

**Pull request merged**
