### PR TITLE
Search

### PR DESCRIPTION
**Pull request by jbakosi**
Good enough as a basic infrastructure for server and client.

There is a lot of changes here:
* pretty much a complete rewrite of both daemon (server) and client (cli)
* networking via zmq
* search via xapian
* db via xapian's db
* logging via easylogging++
* server command line args via boost::program_options
* server is now threaded (via `std::thread`): 'server' thread does networking (serves clients), 'db' thread deals with db indexing and searching (another one in the future could do p2p sync of the db)
* and more ...

Next, in this order:

0. Add some tests of existing basic functionality
1. Add more realistic db ad entries, see doc/search.txt
2. Add syncing db to peers

### CODE REVIEW

**Comment by layters** [comment]
Ew, Xapian is GPL. I refuse to switch the license to a less permissive license than MIT/BSD-3.

**Comment by jbakosi** [comment]
Can you explain why you don't like GPL for something like neroshop, likely an end-application (not a library)?

**Comment by layters** [comment]
It's just a matter of preference. I will approve the commit anyways. I'm curious to see how this turns out.

**Review by layters — APPROVED** [review]

**Comment by jbakosi** [comment]
Okay, so you don't really have a reason? This is _not_ something like I like apples but dislike bananas.

**Comment by jbakosi** [comment]
Did you even look at the code? The point of doing a PR (and a review) is (1) to find problems, and (2) the reviewer(s) also learn and get familiar with the code, (3) have a constructive discussion on how things could be done better. If you just approve, that can mean either of two things: you either completely understand everything and have no comment (which I highly doubt), or (2) you have not even looked at it and don't even care.

**Comment by layters** [comment]
I _always_ look at the code before reviewing it. I didn't look at all of it this time (I'm currently doing that now)

**Comment by jbakosi** [comment]
There is not need to do a PR, other than the reasons I mention above. I could just push to 'main', but then there is no chance of any of that happen. If you just approve, there is no need for a PR.

**Comment by layters** [comment]
Then get everyone to review it. There are 4 contributors for this project, I'm not the only one.

**Comment by jbakosi** [comment]
I can request everyone but so far no one else even made a comment on any PR I submitted. At least you engage in a conversation. ;-)

**Comment by jbakosi** [comment]
I added everyone I could. Two more reviewers.

**Comment by layters** [comment]
2 reviewers should be enough. I doubt everyone will review though.

**Pull request closed without merging**
