### PR TITLE
Revamp cmake build system

### PR DESCRIPTION
**Pull request by jbakosi**
This changes the build system to a more automated one and to one that should be less painful for neroshop developers.

New build instructions (also in `doc/build.txt`):

```shell
# clone neroshop
git clone https://github.com/neroshop/neroshop.git && cd neroshop
# build external libs
mkdir -p external/build && cd external/build && cmake .. && make && cd -
# build neroshop
mkdir build && cd build && cmake .. && make
```

It is assumed that prerequisites for building monero and monero-cpp are installed.

Please let me know what you think.

### CODE REVIEW

**Comment by TheXCoders** [comment]
It seems a lot more optimized than before. And more simpler to use. Sounds good to me.

**Review by ghost — APPROVED** [review]
this looks a lot less painful, good work 👍️

**Review by TheXCoders — APPROVED** [review]

**Review by layters — APPROVED** [review]

**Comment by jbakosi** [comment]
Thanks, so anyone had any trouble? Especially on different linux distros? E.g., build problems due to libraries not found that I assumed exist? Any problems?

**Comment by jbakosi** [comment]
Also, note, that for now, neroshop-gui is disabled as a target, we only build the server/daemon, neromon, because we need to start with that and continue with a cli, and only then go on to a gui. So the nerohsop build is really very fast at this point since we don't build a bunch of stuff that used to be built. ;-) But that will grow of course. I think we can start working on the server and the cli pretty much concurrently.

**Comment by ghost** [comment]
> Thanks, so anyone had any trouble? Especially on different linux distros? E.g., build problems due to libraries not found that I assumed exist? Any problems?

ran the command `cmake ../` without actually building the thing, my bad.
error is:

```
[ 33%] Building CXX object CMakeFiles/neromon.dir/src/daemon.cpp.o
In file included from /home/canadianwotaku/Code/neroshop-build/src/daemon.cpp:15:
/home/canadianwotaku/Code/neroshop-build/src/server.hpp:8:10: fatal error: linux_header.hpp: No such file or directory
    8 | #include "linux_header.hpp"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/neromon.dir/build.make:76: CMakeFiles/neromon.dir/src/daemon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/neromon.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by jbakosi** [comment]
If I remember correctly, `linux_header.hpp` is part of [dokun-ui](https://github.com/larteyoh/dokun-ui), which should be built and installed by the TPL build, which should be done _before_ the code/neroshop build. That should install the dokun-ui headers (but only after the patch is applied by cmake, which creates the correct install target for the include files), and then the neroshop daemon should find that header.

The patch in [cmake/dokun-ui.patch](https://github.com/neroshop/neroshop/pull/15/files#diff-39d8b4a418c1a59a39ee45457135feed27646e1ce5ee12bba2d6583c04314746) applies https://github.com/larteyoh/dokun-ui/pull/1, so that will go away, once this latter is merged.

**Comment by jbakosi** [comment]
`linux_header.hpp` should be installed under `neroshop/external/install/gnu-x86_64/include/dokun-ui/`.

**Comment by jbakosi** [comment]
Okay, I think what you might have is the relative locations of `external` and the (neroshop) `build` might be different. What is assumed by default is that `<neroshop>/external/install` will contain the TPL install and that `<neroshop>/build` will be the build dir. The names do not matter much, but the relative locations do. If you want to use different locations, you can pass to the neroshop cmake the argument `-DTPL_DIR=<path-to-your-favorite-external-install>`. What's important that this directory points to a path where cmake will find a directory structure populated by the previous cmake/make step that built the TPLs, e.g., `path-to-your-favorite-external-install>/include,` `<path-to-your-favorite-external-install>/include/common`, `<path-to-your-favorite-external-install>/include/common`, etc. See also `neroshop/CMakeLists.txt` lines 57 and 63.

**Comment by jbakosi** [comment]
I will document the various options a little better.

**Pull request merged**
