### PR TITLE
Peer Discovery (WIP)

### PR DESCRIPTION
**Pull request by ghost**
Pull request for implementing peer discovery.

### CODE REVIEW

**Comment by ghost** [comment]
i don't know what happened there, but it's fixed now

**Comment by jbakosi** [comment]
Hey @canadianotaku : Let me know if you need my help in translating these changes to be compatible with #15. Thanks.

**Comment by ghost** [comment]
it would be easier for me to just redo this from scratch, as the changes i've made have virtually no difference to the main branch

**Comment by jbakosi** [comment]
Okay, sounds good. Based on the new build, I think you will get the idea: all external libs are now cloned from a git repo by cmake so there is no need to mess with git submodules. I find this is a bit less complex. Still, let me know if you have questions or if something does not work. Thanks.

**Pull request closed without merging**
